title: Meta Schema
description: 'Added fields that are derived from an event''s data/fields after it
  is has been logged or stored and more specifically could change based on future
  information. In the simplest form, this would include enrichments of the data.

  A good example, would be the Autonomous System Number lookup of an IP address. The
  reason, is because an IP address on 2018-01-01 may belong to one entity and the
  later in the future could be acquired by a new entity and thus the data from 2018-01-01
  may be different than say 2022-01-01. Actually, a great example of this example
  is the IP address <code>1.1.1.1</code> that for a long time belonged to APNIC, and
  then was acquired by Cloudflare in 2019. The Meta schema, is a way that can help
  aide an analyst to know the field they are looking at may be derived from a data
  source or calculation that could change over time.'
data_fields:
- standard_name: category
  field_name: ''
  type: string
  description: 'Description to define a grouping of a value. Commonly used for URL/domain
    category (ie: Adult, Abuse, Parked, RFC-1918, etc)'
  sample_value: '``'
- standard_name: ttp
  field_name: ''
  type: string
  description: Tactic, technique, and procedure
  sample_value: '``'
- standard_name: alert
  field_name: ''
  type: string
  description: Data describing an alert
  sample_value: '``'
- standard_name: geo location
  field_name: ''
  type: geo_point
  description: Geo longitude and latitude point of a field
  sample_value: '``'
- standard_name: AS Number
  field_name: ''
  type: integer
  description: Autonomous System (AS) number (BGP AS Number)
  sample_value: '``'
- standard_name: AS Org
  field_name: ''
  type: string
  description: Autonomous System (AS) organization (BGP AS Name)
  sample_value: '``'
resources: []
tags: []
