title: Services Table
operating system: windows
data channel: osquery
description: List all installed Windows services and their relevant data.
data fields:
- standard name: service_name
  field name: name
  type: TEXT
  description: Service name
  sample value: ''
- standard name: service_type
  field name: service_type
  type: TEXT
  description: 'Service Type: OWN_PROCESS, SHARE_PROCESS and maybe Interactive (can
    interact with the desktop)'
  sample value: ''
- standard name: service_display_name
  field name: display_name
  type: TEXT
  description: Service Display name
  sample value: ''
- standard name: service_status
  field name: status
  type: TEXT
  description: 'Service Current status: STOPPED, START_PENDING, STOP_PENDING, RUNNING,
    CONTINUE_PENDING, PAUSE_PENDING, PAUSED'
  sample value: ''
- standard name: process_id
  field name: pid
  type: INTEGER
  description: the Process ID of the service
  sample value: ''
- standard name: service_start_type
  field name: start_type
  type: TEXT
  description: 'Service start type: BOOT_START, SYSTEM_START, AUTO_START, DEMAND_START,
    DISABLED'
  sample value: ''
- standard name: service_error_code
  field name: win32_exit_code
  type: INTEGER
  description: The error code that the service uses to report an error that occurs
    when it is starting or stopping
  sample value: ''
- standard name: service_exit_code
  field name: service_exit_code
  type: INTEGER
  description: The service-specific error code that the service returns when an error
    occurs while the service is starting or stopping
  sample value: ''
- standard name: file_path
  field name: path
  type: TEXT
  description: Path to Service Executable
  sample value: ''
- standard name: module_path
  field name: module_path
  type: TEXT
  description: Path to ServiceDll
  sample value: ''
- standard name: service_description
  field name: description
  type: TEXT
  description: Service Description
  sample value: ''
- standard name: user_name
  field name: user_account
  type: TEXT
  description: The name of the account that the service process will be logged on
    as when it runs. This name can be of the form Domain\UserName. If the account
    belongs to the built-in domain, the name can be of the form .\UserName.
  sample value: ''
resources:
- text: osquery GitHub
  link: https://github.com/facebook/osquery/blob/master/specs/windows/services.table
tags: null